print ("Hello, everybody.")
print ("Let's see what we can do here.")
print ("I've opened my GitHub and am watching the provided video.")
print ("I see some of us are having problems.")
print ("The instructions seem outdated.")
print ("I wonder if that is intentional to see what we will do?")
print ("Here's what I did.")
print ("As you can see, I first created a new code for this exercise.")
print ("Under Replit Tools, select Git, and then click on Git Repository.")
print ("Here I am experimenting to see if this worked.")
print ("I can't seem to get to the VERSION CONTROL or PUSH function.")
print ("It might be due to older versions of GitHub being used.")
print ("It now appears to work. I need to review. It is late and I'm quite drowsy.")
print ("I reviewed this Tuesday morning as I had a long day at work yesterday.")
print ("I found a link on GOOGLE that explains how to connect GitHub and Replit.")
print ("I'm now connected and will post that link on my Wk 10 Discussion page.")
print ("Now to experiment with the VERSION CONTROL and PUSH functions.")
print ("It is now Wednesday morning and here I am.")
print ("Isn't technology fun? To really screw things up takes a computer.")
print ("Does blue represent new code changes?")
print ("Does green represent past changes?")